- hosts: aws_ec2
  gather_facts: no
  tasks:
    - name: check ssh port 22
      wait_for:
        port: 22
        state: started
        host: "{{ inventory_hostname }}"
        connect_timeout: 5
        timeout: 5
      delegate_to: localhost
      ignore_errors: yes
      register: ssh_port

    - name: check ssh port 2222
      wait_for:
        port: 2222
        state: started
        host: "{{ inventory_hostname }}"
        connect_timeout: 5
        timeout: 5
      delegate_to: localhost
      ignore_errors: yes
      register: ssh_port_default
      when: 
        - ssh_port is defined 
        - ssh_port.state is undefined

    - name: set ansible_port 2222
      set_fact:
        ansible_port: 2222
      when: ssh_port_default.state is defined

- hosts: aws_ec2
  tasks:
    - name: change ssh port
      register: ssh_port_changed
      lineinfile:
        dest: "/etc/ssh/sshd_config"
        regexp: "^Port"
        line: "Port 2222"

    - name: restart sshd
      service:
        name: sshd
        state: restarted
      when:
        - ssh_port_changed is defined

    - name: change ansible_port
      set_fact:
        ansible_port: 2222

    - name: create new user
      user:
        name: hello
        password: hello123!!
        groups:
          - wheel
        shell: /bin/bash
        state: present

    - name: enable nginx package
      command: amazon-linux-extras enable nginx1

    - name: install nginx
      package:
        name: nginx
        state: present

    - name: add content to nginx
      copy:
        content: "Hello, Ansible!"
        dest: "/usr/share/nginx/html/index.html"

    - name: start nginx
      service:
        name: nginx
        state: started
        enabled: true
